In [2893]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [2894]:
path = 'international.csv'

In [2895]:
path3 = 'fifa2018.csv'
path4 = 'fifa192014.csv'

In [2896]:
n = pd.read_csv(path3)
m = pd.read_csv(path4)

In [2897]:
n

,Datetime (Brazil),Stage,Stadium,City,Home Team,Home Team Goals,Away Team Goals,Away Team,Win Conditions,Penalty,Win,Total Goals,Attendance
0,12:00�-�14 de Jun 2018,Group A,Luzhniki Stadium,Moscow,Russia,5,0,Saudi Arabia,Normal Time,NaN,Russia,5,78011
1,09:00�-�15 de Jun 2018,Group A,Ekaterinburg Arena,Ekaterinburg,Egypt,0,1,Uruguay,Normal Time,NaN,Uruguay,1,27015
2,12:00�-�15 de Jun 2018,Group B,Saint Petersburg Stadium,St. Petersburg,Morocco,0,1,IR Iran,Normal Time,NaN,IR Iran,1,62548
3,15:00�-�15 de Jun 2018,Group B,Fisht Stadium,Sochi,Portugal,3,3,Spain,Normal Time,NaN,Empate,6,43866
4,07:00�-�16 de Jun 2018,Group C,Kazan Arena,Kazan,France,2,1,Australia,Normal Time,NaN,France,3,41279
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,15:00 - 07 de Jul 2018,Quarter-finals,Fisht Stadium,Sochi,Russia,2,2,Croatia,Penalty,(3-4),Croatia,4,44287
60,15:00 - 10 de Jul 2018,Semi-finals,Saint Petersburg Stadium,St. Petersburg,France,1,0,Belgium,Normal Time,NaN,France,1,64286
61,15:00 - 11 de Jul 2018,Semi-finals,Luzhniki Stadium,Moscow,Croatia,2,1,England,Extend,NaN,Croatia,3,78011
62,11:00 - 14 de Jul 2018,Play-off for third place,Saint Petersburg Stadium,St. Petersburg,Belgium,2,0,England,Normal Time,NaN,Belgium,2,64406
63,12:00 - 15 de Jul 2018,Final,Luzhniki Stadium,Moscow,France,4,2,Croatia,Normal Time,NaN,France,6,78011

In [2898]:
m.dropna(inplace=True)

In [2899]:
n['Datetime (Brazil)'] = (
    n['Datetime (Brazil)']
    .str.replace('�-�', ' ', regex=False)
    .str.replace(r'^\d{2}:\d{2}\s*', '', regex=True)
    .str.replace(' de ', ' ', regex=False)
    .str.replace('-', ' ', regex=False)
)

In [2900]:
n

,Datetime (Brazil),Stage,Stadium,City,Home Team,Home Team Goals,Away Team Goals,Away Team,Win Conditions,Penalty,Win,Total Goals,Attendance
0,14 Jun 2018,Group A,Luzhniki Stadium,Moscow,Russia,5,0,Saudi Arabia,Normal Time,NaN,Russia,5,78011
1,15 Jun 2018,Group A,Ekaterinburg Arena,Ekaterinburg,Egypt,0,1,Uruguay,Normal Time,NaN,Uruguay,1,27015
2,15 Jun 2018,Group B,Saint Petersburg Stadium,St. Petersburg,Morocco,0,1,IR Iran,Normal Time,NaN,IR Iran,1,62548
3,15 Jun 2018,Group B,Fisht Stadium,Sochi,Portugal,3,3,Spain,Normal Time,NaN,Empate,6,43866
4,16 Jun 2018,Group C,Kazan Arena,Kazan,France,2,1,Australia,Normal Time,NaN,France,3,41279
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,07 Jul 2018,Quarter-finals,Fisht Stadium,Sochi,Russia,2,2,Croatia,Penalty,(3-4),Croatia,4,44287
60,10 Jul 2018,Semi-finals,Saint Petersburg Stadium,St. Petersburg,France,1,0,Belgium,Normal Time,NaN,France,1,64286
61,11 Jul 2018,Semi-finals,Luzhniki Stadium,Moscow,Croatia,2,1,England,Extend,NaN,Croatia,3,78011
62,14 Jul 2018,Play-off for third place,Saint Petersburg Stadium,St. Petersburg,Belgium,2,0,England,Normal Time,NaN,Belgium,2,64406
63,15 Jul 2018,Final,Luzhniki Stadium,Moscow,France,4,2,Croatia,Normal Time,NaN,France,6,78011

In [2901]:
n['Datetime (Brazil)'] = pd.to_datetime(
    n['Datetime (Brazil)'],
    format='mixed'##'%d %b %Y',
    # errors='coerce'
).dt.strftime('%Y-%m-%d')

In [2902]:
n

,Datetime (Brazil),Stage,Stadium,City,Home Team,Home Team Goals,Away Team Goals,Away Team,Win Conditions,Penalty,Win,Total Goals,Attendance
0,2018-06-14,Group A,Luzhniki Stadium,Moscow,Russia,5,0,Saudi Arabia,Normal Time,NaN,Russia,5,78011
1,2018-06-15,Group A,Ekaterinburg Arena,Ekaterinburg,Egypt,0,1,Uruguay,Normal Time,NaN,Uruguay,1,27015
2,2018-06-15,Group B,Saint Petersburg Stadium,St. Petersburg,Morocco,0,1,IR Iran,Normal Time,NaN,IR Iran,1,62548
3,2018-06-15,Group B,Fisht Stadium,Sochi,Portugal,3,3,Spain,Normal Time,NaN,Empate,6,43866
4,2018-06-16,Group C,Kazan Arena,Kazan,France,2,1,Australia,Normal Time,NaN,France,3,41279
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2018-07-07,Quarter-finals,Fisht Stadium,Sochi,Russia,2,2,Croatia,Penalty,(3-4),Croatia,4,44287
60,2018-07-10,Semi-finals,Saint Petersburg Stadium,St. Petersburg,France,1,0,Belgium,Normal Time,NaN,France,1,64286
61,2018-07-11,Semi-finals,Luzhniki Stadium,Moscow,Croatia,2,1,England,Extend,NaN,Croatia,3,78011
62,2018-07-14,Play-off for third place,Saint Petersburg Stadium,St. Petersburg,Belgium,2,0,England,Normal Time,NaN,Belgium,2,64406
63,2018-07-15,Final,Luzhniki Stadium,Moscow,France,4,2,Croatia,Normal Time,NaN,France,6,78011

In [2903]:
m.tail()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4),63267.0,0.0,0.0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

In [2904]:
m.columns.to_list()

['Year',
 'Datetime',
 'Stage',
 'Stadium',
 'City',
 'Home Team Name',
 'Home Team Goals',
 'Away Team Goals',
 'Away Team Name',
 'Win conditions',
 'Attendance',
 'Half-time Home Goals',
 'Half-time Away Goals',
 'Referee',
 'Assistant 1',
 'Assistant 2',
 'RoundID',
 'MatchID',
 'Home Team Initials',
 'Away Team Initials']

In [2905]:
m.sort_values(['Year','Datetime'], inplace=True, ascending=False)

In [2906]:
n.head()

,Datetime (Brazil),Stage,Stadium,City,Home Team,Home Team Goals,Away Team Goals,Away Team,Win Conditions,Penalty,Win,Total Goals,Attendance
0,2018-06-14,Group A,Luzhniki Stadium,Moscow,Russia,5,0,Saudi Arabia,Normal Time,NaN,Russia,5,78011
1,2018-06-15,Group A,Ekaterinburg Arena,Ekaterinburg,Egypt,0,1,Uruguay,Normal Time,NaN,Uruguay,1,27015
2,2018-06-15,Group B,Saint Petersburg Stadium,St. Petersburg,Morocco,0,1,IR Iran,Normal Time,NaN,IR Iran,1,62548
3,2018-06-15,Group B,Fisht Stadium,Sochi,Portugal,3,3,Spain,Normal Time,NaN,Empate,6,43866
4,2018-06-16,Group C,Kazan Arena,Kazan,France,2,1,Australia,Normal Time,NaN,France,3,41279

In [2907]:
n.sort_values(['Datetime (Brazil)'], inplace=True, ascending=False)

In [2908]:
n.columns.to_list()

['Datetime (Brazil)',
 'Stage',
 'Stadium',
 'City',
 'Home Team',
 'Home Team Goals',
 'Away Team Goals',
 'Away Team',
 'Win Conditions',
 'Penalty',
 'Win',
 'Total Goals',
 'Attendance']

In [2909]:
n = n[['Datetime (Brazil)',
 'Home Team',
 'Away Team',
 'Home Team Goals',
 'Away Team Goals'
]]

In [2910]:
p = ['Year',
 'Datetime',
 'Home Team Name',
 'Away Team Name',
 'Home Team Goals',
 'Away Team Goals',
]

In [2911]:
m = m[p].reset_index(drop=True)

In [2912]:
n = n.reset_index(drop=True)

In [2913]:
m

,Year,Datetime,Home Team Name,Away Team Name,Home Team Goals,Away Team Goals
0,2014.0,30 Jun 2014 - 13:00,France,Nigeria,2.0,0.0
1,2014.0,30 Jun 2014 - 13:00,France,Nigeria,2.0,0.0
2,2014.0,29 Jun 2014 - 17:00,Costa Rica,Greece,1.0,1.0
3,2014.0,29 Jun 2014 - 17:00,Costa Rica,Greece,1.0,1.0
4,2014.0,29 Jun 2014 - 13:00,Netherlands,Mexico,2.0,1.0
...,...,...,...,...,...,...
845,1930.0,15 Jul 1930 - 16:00,Argentina,France,1.0,0.0
846,1930.0,14 Jul 1930 - 14:50,Romania,Peru,3.0,1.0
847,1930.0,14 Jul 1930 - 12:45,Yugoslavia,Brazil,2.0,1.0
848,1930.0,13 Jul 1930 - 15:00,France,Mexico,4.0,1.0
849,1930.0,13 Jul 1930 - 15:00,USA,Belgium,3.0,0.0

In [2914]:
m.rename(columns={'Datetime':'date','Home Team Name': 'home_team', 'Away Team Name': 'away_team','Home Team Goals': 'home_score',	'Away Team Goals':'away_score'}, inplace= True)

In [2915]:
n.rename(columns={'Datetime (Brazil)':'date','Home Team': 'home_team', 'Away Team': 'away_team','Home Team Goals': 'home_score',	'Away Team Goals':'away_score'}, inplace= True)

In [2916]:
conditions = [m['home_score'] > m['away_score'], m['home_score'] < m['away_score'], m['home_score'] == m['away_score']]
choices = [2, 0, 1]
m['Result'] = np.select(conditions, choices, default=0)

In [2917]:
conditions = [n['home_score'] > n['away_score'], n['home_score'] < n['away_score'], n['home_score'] == n['away_score']]
choices = [2, 0, 1]
n['Result'] = np.select(conditions, choices, default=0)

In [2918]:
m.head()

,Year,date,home_team,away_team,home_score,away_score,Result
0,2014.0,30 Jun 2014 - 13:00,France,Nigeria,2.0,0.0,2
1,2014.0,30 Jun 2014 - 13:00,France,Nigeria,2.0,0.0,2
2,2014.0,29 Jun 2014 - 17:00,Costa Rica,Greece,1.0,1.0,1
3,2014.0,29 Jun 2014 - 17:00,Costa Rica,Greece,1.0,1.0,1
4,2014.0,29 Jun 2014 - 13:00,Netherlands,Mexico,2.0,1.0,2

In [2919]:
fea = ['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'Result']

In [2920]:
n.sort_values(['date'], inplace=True, ascending=False)

In [2921]:
n

          date home_team     away_team  home_score  away_score  Result
0   2018-07-15    France       Croatia           4           2       2
1   2018-07-14   Belgium       England           2           0       2
2   2018-07-11   Croatia       England           2           1       2
3   2018-07-10    France       Belgium           1           0       2
4   2018-07-07    Sweden       England           0           2       0
..         ...       ...           ...         ...         ...     ...
59  2018-06-16   Croatia       Nigeria           2           0       2
60  2018-06-15     Egypt       Uruguay           0           1       0
61  2018-06-15   Morocco       IR Iran           0           1       0
62  2018-06-15  Portugal         Spain           3           3       1
63  2018-06-14    Russia  Saudi Arabia           5           0       2

[64 rows x 6 columns]

In [2922]:
m = m[fea]

In [2923]:
m['date'] = pd.to_datetime(m['date'], format='mixed')

In [2924]:
m

                   date    home_team away_team  home_score  away_score  Result
0   2014-06-30 13:00:00       France   Nigeria         2.0         0.0       2
1   2014-06-30 13:00:00       France   Nigeria         2.0         0.0       2
2   2014-06-29 17:00:00   Costa Rica    Greece         1.0         1.0       1
3   2014-06-29 17:00:00   Costa Rica    Greece         1.0         1.0       1
4   2014-06-29 13:00:00  Netherlands    Mexico         2.0         1.0       2
..                  ...          ...       ...         ...         ...     ...
845 1930-07-15 16:00:00    Argentina    France         1.0         0.0       2
846 1930-07-14 14:50:00      Romania      Peru         3.0         1.0       2
847 1930-07-14 12:45:00   Yugoslavia    Brazil         2.0         1.0       2
848 1930-07-13 15:00:00       France    Mexico         4.0         1.0       2
849 1930-07-13 15:00:00          USA   Belgium         3.0         0.0       2

[850 rows x 6 columns]

In [2925]:
df = pd.read_csv(path)

In [2926]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
41581,2020-01-10,Barbados,Canada,1,4,Friendly,Irvine,United States,True
41582,2020-01-12,Kosovo,Sweden,0,1,Friendly,Doha,Qatar,True
41583,2020-01-15,Canada,Iceland,0,1,Friendly,Irvine,United States,True
41584,2020-01-19,El Salvador,Iceland,0,1,Friendly,Carson,United States,True
41585,2020-02-01,United States,Costa Rica,1,0,Friendly,Carson,United States,False

In [2927]:
df.isna().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [2928]:
df.columns.to_list()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tournament',
 'city',
 'country',
 'neutral']

In [2929]:
# for i in range(len(df)):
#     if df.loc[i, 'home_score'] > df.loc[i, 'away_score']:
#         df.loc[i, 'Result'] = 'Home'
#     elif df.loc[i, 'home_score'] < df.loc[i, 'away_score']:
#         df.loc[i, 'Result'] = 'Away'
#     else:
#         df.loc[i, 'Result'] = 'Away'

import numpy as np

In [2930]:
conditions = [df['home_score'] > df['away_score'], df['home_score'] < df['away_score'], df['home_score'] == df['away_score']]

In [2931]:
choices = [2, 0, 1]

In [2932]:
df['Result'] = np.select(conditions, choices, default=0)

In [2933]:
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,Result
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False,1
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False,2
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False,2
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False,1
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False,2
...,...,...,...,...,...,...,...,...,...,...
41581,2020-01-10,Barbados,Canada,1,4,Friendly,Irvine,United States,True,0
41582,2020-01-12,Kosovo,Sweden,0,1,Friendly,Doha,Qatar,True,0
41583,2020-01-15,Canada,Iceland,0,1,Friendly,Irvine,United States,True,0
41584,2020-01-19,El Salvador,Iceland,0,1,Friendly,Carson,United States,True,0
41585,2020-02-01,United States,Costa Rica,1,0,Friendly,Carson,United States,False,2

In [2934]:
df.sort_values(['date'], ascending=False, inplace=True)

In [2935]:
df.columns.to_list()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tournament',
 'city',
 'country',
 'neutral',
 'Result']

In [2936]:
features = ['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'Result']

In [2937]:
matches = df[features]

In [2938]:
matches

             date      home_team   away_team  home_score  away_score  Result
41585  2020-02-01  United States  Costa Rica           1           0       2
41584  2020-01-19    El Salvador     Iceland           0           1       0
41583  2020-01-15         Canada     Iceland           0           1       0
41582  2020-01-12         Kosovo      Sweden           0           1       0
41581  2020-01-10       Barbados      Canada           1           4       0
...           ...            ...         ...         ...         ...     ...
4      1876-03-04       Scotland     England           3           0       2
3      1875-03-06        England    Scotland           2           2       1
2      1874-03-07       Scotland     England           2           1       2
1      1873-03-08        England    Scotland           4           2       2
0      1872-11-30       Scotland     England           0           0       1

[41586 rows x 6 columns]

In [2939]:
m['date'] = pd.to_datetime(m['date']).dt.date

In [2940]:
m

           date    home_team away_team  home_score  away_score  Result
0    2014-06-30       France   Nigeria         2.0         0.0       2
1    2014-06-30       France   Nigeria         2.0         0.0       2
2    2014-06-29   Costa Rica    Greece         1.0         1.0       1
3    2014-06-29   Costa Rica    Greece         1.0         1.0       1
4    2014-06-29  Netherlands    Mexico         2.0         1.0       2
..          ...          ...       ...         ...         ...     ...
845  1930-07-15    Argentina    France         1.0         0.0       2
846  1930-07-14      Romania      Peru         3.0         1.0       2
847  1930-07-14   Yugoslavia    Brazil         2.0         1.0       2
848  1930-07-13       France    Mexico         4.0         1.0       2
849  1930-07-13          USA   Belgium         3.0         0.0       2

[850 rows x 6 columns]

In [2941]:
matches.reset_index(drop=True)

             date      home_team   away_team  home_score  away_score  Result
0      2020-02-01  United States  Costa Rica           1           0       2
1      2020-01-19    El Salvador     Iceland           0           1       0
2      2020-01-15         Canada     Iceland           0           1       0
3      2020-01-12         Kosovo      Sweden           0           1       0
4      2020-01-10       Barbados      Canada           1           4       0
...           ...            ...         ...         ...         ...     ...
41581  1876-03-04       Scotland     England           3           0       2
41582  1875-03-06        England    Scotland           2           2       1
41583  1874-03-07       Scotland     England           2           1       2
41584  1873-03-08        England    Scotland           4           2       2
41585  1872-11-30       Scotland     England           0           0       1

[41586 rows x 6 columns]

In [2942]:
matches = pd.concat([m, matches], ignore_index=True)

In [2943]:
matches = pd.concat([n, matches], ignore_index=True)

In [2944]:
matches

             date home_team away_team  home_score  away_score  Result
0      2018-07-15    France   Croatia         4.0         2.0       2
1      2018-07-14   Belgium   England         2.0         0.0       2
2      2018-07-11   Croatia   England         2.0         1.0       2
3      2018-07-10    France   Belgium         1.0         0.0       2
4      2018-07-07    Sweden   England         0.0         2.0       0
...           ...       ...       ...         ...         ...     ...
42495  1876-03-04  Scotland   England         3.0         0.0       2
42496  1875-03-06   England  Scotland         2.0         2.0       1
42497  1874-03-07  Scotland   England         2.0         1.0       2
42498  1873-03-08   England  Scotland         4.0         2.0       2
42499  1872-11-30  Scotland   England         0.0         0.0       1

[42500 rows x 6 columns]

In [2945]:
path2 = 'fifa_world_cup.csv'

In [2946]:
match2 = pd.read_csv(path2)

In [2947]:
match2.columns.to_list()

['team1',
 'team2',
 'possession team1',
 'possession team2',
 'possession in contest',
 'number of goals team1',
 'number of goals team2',
 'date',
 'hour',
 'category',
 'total attempts team1',
 'total attempts team2',
 'conceded team1',
 'conceded team2',
 'goal inside the penalty area team1',
 'goal inside the penalty area team2',
 'goal outside the penalty area team1',
 'goal outside the penalty area team2',
 'assists team1',
 'assists team2',
 'on target attempts team1',
 'on target attempts team2',
 'off target attempts team1',
 'off target attempts team2',
 'attempts inside the penalty area team1',
 'attempts inside the penalty area  team2',
 'attempts outside the penalty area  team1',
 'attempts outside the penalty area  team2',
 'left channel team1',
 'left channel team2',
 'left inside channel team1',
 'left inside channel team2',
 'central channel team1',
 'central channel team2',
 'right inside channel team1',
 'right inside channel team2',
 'right channel team1',
 'right channel team2',
 'total offers to receive team1',
 'total offers to receive team2',
 'inbehind offers to receive team1',
 'inbehind offers to receive team2',
 'inbetween offers to receive team1',
 'inbetween offers to receive team2',
 'infront offers to receive team1',
 'infront offers to receive team2',
 'receptions between midfield and defensive lines team1',
 'receptions between midfield and defensive lines team2',
 'attempted line breaks team1',
 'attempted line breaks team2',
 'completed line breaksteam1',
 'completed line breaks team2',
 'attempted defensive line breaks team1',
 'attempted defensive line breaks team2',
 'completed defensive line breaksteam1',
 'completed defensive line breaks team2',
 'yellow cards team1',
 'yellow cards team2',
 'red cards team1',
 'red cards team2',
 'fouls against team1',
 'fouls against team2',
 'offsides team1',
 'offsides team2',
 'passes team1',
 'passes team2',
 'passes completed team1',
 'passes completed team2',
 'crosses team1',
 'crosses team2',
 'crosses completed team1',
 'crosses completed team2',
 'switches of play completed team1',
 'switches of play completed team2',
 'corners team1',
 'corners team2',
 'free kicks team1',
 'free kicks team2',
 'penalties scored team1',
 'penalties scored team2',
 'goal preventions team1',
 'goal preventions team2',
 'own goals team1',
 'own goals team2',
 'forced turnovers team1',
 'forced turnovers team2',
 'defensive pressures applied team1',
 'defensive pressures applied team2']

In [2948]:
features2 = [ 'date', 'team1',
 'team2',
 'number of goals team1',
 'number of goals team2',
 ]

In [2949]:
match2 = match2[features2]

In [2950]:
match2

,date,team1,team2,number of goals team1,number of goals team2
0,20 NOV 2022,QATAR,ECUADOR,0,2
1,21 NOV 2022,ENGLAND,IRAN,6,2
2,21 NOV 2022,SENEGAL,NETHERLANDS,0,2
3,21 NOV 2022,UNITED STATES,WALES,1,1
4,22 NOV 2022,ARGENTINA,SAUDI ARABIA,1,2
...,...,...,...,...,...
59,10 DEC 2022,ENGLAND,FRANCE,1,2
60,13 DEC 2022,ARGENTINA,CROATIA,3,0
61,14 DEC 2022,FRANCE,MOROCCO,2,0
62,17 DEC 2022,CROATIA,MOROCCO,2,1
63,18 DEC 2022,ARGENTINA,FRANCE,3,3

In [2951]:
match2.rename(columns={'team1':'home_team', 'team2':'away_team','number of goals team1':'home_score', 'number of goals team2':'away_score'}, inplace=True)

In [2952]:
match2

           date      home_team     away_team  home_score  away_score
0   20 NOV 2022          QATAR       ECUADOR           0           2
1   21 NOV 2022        ENGLAND          IRAN           6           2
2   21 NOV 2022        SENEGAL   NETHERLANDS           0           2
3   21 NOV 2022  UNITED STATES         WALES           1           1
4   22 NOV 2022      ARGENTINA  SAUDI ARABIA           1           2
..          ...            ...           ...         ...         ...
59  10 DEC 2022        ENGLAND        FRANCE           1           2
60  13 DEC 2022      ARGENTINA       CROATIA           3           0
61  14 DEC 2022         FRANCE       MOROCCO           2           0
62  17 DEC 2022        CROATIA       MOROCCO           2           1
63  18 DEC 2022      ARGENTINA        FRANCE           3           3

[64 rows x 5 columns]

In [2953]:
match2['date'] = pd.to_datetime(match2['date'])

C:\Users\hp\AppData\Local\Temp\ipykernel_31580\153562456.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  match2['date'] = pd.to_datetime(match2['date'])

In [2954]:
match2

         date      home_team     away_team  home_score  away_score
0  2022-11-20          QATAR       ECUADOR           0           2
1  2022-11-21        ENGLAND          IRAN           6           2
2  2022-11-21        SENEGAL   NETHERLANDS           0           2
3  2022-11-21  UNITED STATES         WALES           1           1
4  2022-11-22      ARGENTINA  SAUDI ARABIA           1           2
..        ...            ...           ...         ...         ...
59 2022-12-10        ENGLAND        FRANCE           1           2
60 2022-12-13      ARGENTINA       CROATIA           3           0
61 2022-12-14         FRANCE       MOROCCO           2           0
62 2022-12-17        CROATIA       MOROCCO           2           1
63 2022-12-18      ARGENTINA        FRANCE           3           3

[64 rows x 5 columns]

In [2955]:
# for n in range(len(match2)):
#     if match2.loc[n, 'home_score'] > match2.loc[n, 'away_score']:
#         match2.loc[n, 'Result'] = 'Home'
#     elif match2.loc[n, 'home_score'] < match2.loc[n, 'away_score']:
#         match2.loc[n, 'Result'] = 'Away'
#     else:
#         match2.loc[n, 'Result'] = 'Draw'

conditions2 = [match2['home_score'] > match2['away_score'], match2['home_score'] < match2['away_score'], match2['home_score'] == match2['away_score']]

In [2956]:
choice2 = [2, 0, 1]

In [2957]:
match2['Result'] = np.select(conditions2, choice2, default=0)

In [2958]:
match2

         date      home_team     away_team  home_score  away_score  Result
0  2022-11-20          QATAR       ECUADOR           0           2       0
1  2022-11-21        ENGLAND          IRAN           6           2       2
2  2022-11-21        SENEGAL   NETHERLANDS           0           2       0
3  2022-11-21  UNITED STATES         WALES           1           1       1
4  2022-11-22      ARGENTINA  SAUDI ARABIA           1           2       0
..        ...            ...           ...         ...         ...     ...
59 2022-12-10        ENGLAND        FRANCE           1           2       0
60 2022-12-13      ARGENTINA       CROATIA           3           0       2
61 2022-12-14         FRANCE       MOROCCO           2           0       2
62 2022-12-17        CROATIA       MOROCCO           2           1       2
63 2022-12-18      ARGENTINA        FRANCE           3           3       1

[64 rows x 6 columns]

In [2959]:
match2.sort_values(['date'], ascending=False, inplace=True)

In [2960]:
match2

         date      home_team     away_team  home_score  away_score  Result
63 2022-12-18      ARGENTINA        FRANCE           3           3       1
62 2022-12-17        CROATIA       MOROCCO           2           1       2
61 2022-12-14         FRANCE       MOROCCO           2           0       2
60 2022-12-13      ARGENTINA       CROATIA           3           0       2
59 2022-12-10        ENGLAND        FRANCE           1           2       0
..        ...            ...           ...         ...         ...     ...
4  2022-11-22      ARGENTINA  SAUDI ARABIA           1           2       0
2  2022-11-21        SENEGAL   NETHERLANDS           0           2       0
1  2022-11-21        ENGLAND          IRAN           6           2       2
3  2022-11-21  UNITED STATES         WALES           1           1       1
0  2022-11-20          QATAR       ECUADOR           0           2       0

[64 rows x 6 columns]

In [2961]:
fifa = pd.concat([match2, matches], ignore_index=True)

In [2962]:
fifa

,date,home_team,away_team,home_score,away_score,Result
0,2022-12-18 00:00:00,ARGENTINA,FRANCE,3.0,3.0,1
1,2022-12-17 00:00:00,CROATIA,MOROCCO,2.0,1.0,2
2,2022-12-14 00:00:00,FRANCE,MOROCCO,2.0,0.0,2
3,2022-12-13 00:00:00,ARGENTINA,CROATIA,3.0,0.0,2
4,2022-12-10 00:00:00,ENGLAND,FRANCE,1.0,2.0,0
...,...,...,...,...,...,...
42559,1876-03-04,Scotland,England,3.0,0.0,2
42560,1875-03-06,England,Scotland,2.0,2.0,1
42561,1874-03-07,Scotland,England,2.0,1.0,2
42562,1873-03-08,England,Scotland,4.0,2.0,2
42563,1872-11-30,Scotland,England,0.0,0.0,1

In [2963]:
fifa['date'] = pd.to_datetime(fifa['date'])

In [2964]:
fifa

            date  home_team away_team  home_score  away_score  Result
0     2022-12-18  ARGENTINA    FRANCE         3.0         3.0       1
1     2022-12-17    CROATIA   MOROCCO         2.0         1.0       2
2     2022-12-14     FRANCE   MOROCCO         2.0         0.0       2
3     2022-12-13  ARGENTINA   CROATIA         3.0         0.0       2
4     2022-12-10    ENGLAND    FRANCE         1.0         2.0       0
...          ...        ...       ...         ...         ...     ...
42559 1876-03-04   Scotland   England         3.0         0.0       2
42560 1875-03-06    England  Scotland         2.0         2.0       1
42561 1874-03-07   Scotland   England         2.0         1.0       2
42562 1873-03-08    England  Scotland         4.0         2.0       2
42563 1872-11-30   Scotland   England         0.0         0.0       1

[42564 rows x 6 columns]

In [2965]:
fifa['home_team'] = fifa['home_team'].str.title()
fifa['away_team'] = fifa['away_team'].str.title()

In [2966]:
fifa['home_team'].unique

<bound method Series.unique of 0        Argentina
1          Croatia
2           France
3        Argentina
4          England
           ...
42559     Scotland
42560      England
42561     Scotland
42562      England
42563     Scotland
Name: home_team, Length: 42564, dtype: str>

In [2967]:
fifa['home_team'] = fifa['home_team'].str.strip()
fifa['away_team'] = fifa['away_team'].str.strip()

In [2968]:
fifa[fifa['away_team'] == 'Morocco']

            date   home_team away_team  home_score  away_score  Result
1     2022-12-17     Croatia   Morocco         2.0         1.0       2
2     2022-12-14      France   Morocco         2.0         0.0       2
22    2022-12-01      Canada   Morocco         1.0         2.0       0
38    2022-11-27     Belgium   Morocco         0.0         2.0       0
95    2018-06-25       Spain   Morocco         2.0         2.0       1
...          ...         ...       ...         ...         ...     ...
37529 1961-11-23       Spain   Morocco         3.0         2.0       2
37618 1961-06-21   German Dr   Morocco         1.0         2.0       0
37622 1961-06-18  Yugoslavia   Morocco         3.0         2.0       2
37676 1961-04-02       Ghana   Morocco         0.0         0.0       1
37734 1960-11-13     Tunisia   Morocco         2.0         1.0       2

[267 rows x 6 columns]

In [2969]:
# Mapping out Team Form
fifa['home_form'] = fifa['Result'].map({2:3, 0: 0, 1:1})
fifa['away_form'] = fifa['Result'].map({2:0, 0: 3, 1:1})

In [2970]:
fifa.head()

,date,home_team,away_team,home_score,away_score,Result,home_form,away_form
0,2022-12-18,Argentina,France,3.0,3.0,1,1,1
1,2022-12-17,Croatia,Morocco,2.0,1.0,2,3,0
2,2022-12-14,France,Morocco,2.0,0.0,2,3,0
3,2022-12-13,Argentina,Croatia,3.0,0.0,2,3,0
4,2022-12-10,England,France,1.0,2.0,0,0,3

In [2971]:
fifa.head()

,date,home_team,away_team,home_score,away_score,Result,home_form,away_form
0,2022-12-18,Argentina,France,3.0,3.0,1,1,1
1,2022-12-17,Croatia,Morocco,2.0,1.0,2,3,0
2,2022-12-14,France,Morocco,2.0,0.0,2,3,0
3,2022-12-13,Argentina,Croatia,3.0,0.0,2,3,0
4,2022-12-10,England,France,1.0,2.0,0,0,3

In [2972]:
fifa.columns.to_list()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'Result',
 'home_form',
 'away_form']

In [2973]:
training_features = [
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'Result',
 'home_form',
 'away_form']
# output_feature = ['result']

In [2974]:
train_fifa = fifa[training_features]

In [2975]:
train_fifa['home_avg_goal'] = train_fifa.groupby('home_team')['home_score'].transform(
    lambda x: x.shift(1).rolling(window=5).mean()
)
train_fifa['away_avg_goal'] = train_fifa.groupby('away_team')['away_score'].transform(
    lambda x: x.shift(1).rolling(5).mean()
)
train_fifa['home_avg_form'] = train_fifa.groupby('home_team')['home_form'].transform(
    lambda x: x.shift(1).rolling(5).mean()
)
train_fifa['away_avg_form'] = train_fifa.groupby('away_team')['away_form'].transform(
    lambda x: x.shift(1).rolling(5).mean())

In [2976]:
train_fifa

,home_team,away_team,home_score,away_score,Result,home_form,away_form,home_avg_goal,away_avg_goal,home_avg_form,away_avg_form
0,Argentina,France,3.0,3.0,1,1,1,NaN,NaN,NaN,NaN
1,Croatia,Morocco,2.0,1.0,2,3,0,NaN,NaN,NaN,NaN
2,France,Morocco,2.0,0.0,2,3,0,NaN,NaN,NaN,NaN
3,Argentina,Croatia,3.0,0.0,2,3,0,NaN,NaN,NaN,NaN
4,England,France,1.0,2.0,0,0,3,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
42559,Scotland,England,3.0,0.0,2,3,0,6.0,4.6,3.0,1.2
42560,England,Scotland,2.0,2.0,1,1,1,1.8,3.6,1.2,2.4
42561,Scotland,England,2.0,1.0,2,3,0,5.6,4.4,3.0,1.2
42562,England,Scotland,4.0,2.0,2,3,0,2.0,2.8,1.4,2.0
42563,Scotland,England,0.0,0.0,1,1,1,5.0,2.0,3.0,0.6

In [2977]:
train_fifa = train_fifa.dropna()

In [2978]:
train_fifa

,home_team,away_team,home_score,away_score,Result,home_form,away_form,home_avg_goal,away_avg_goal,home_avg_form,away_avg_form
107,Argentina,Croatia,0.0,3.0,0,0,3,2.2,1.4,2.0,1.2
119,Brazil,Switzerland,1.0,1.0,1,1,1,1.6,1.2,2.4,1.2
133,Netherlands,Mexico,2.0,1.0,2,3,0,2.0,0.8,2.2,1.2
151,Croatia,Mexico,1.0,3.0,0,0,3,1.8,1.0,2.2,1.2
164,Uruguay,England,2.0,1.0,2,3,0,1.2,1.2,2.0,1.6
...,...,...,...,...,...,...,...,...,...,...,...
42559,Scotland,England,3.0,0.0,2,3,0,6.0,4.6,3.0,1.2
42560,England,Scotland,2.0,2.0,1,1,1,1.8,3.6,1.2,2.4
42561,Scotland,England,2.0,1.0,2,3,0,5.6,4.4,3.0,1.2
42562,England,Scotland,4.0,2.0,2,3,0,2.0,2.8,1.4,2.0
42563,Scotland,England,0.0,0.0,1,1,1,5.0,2.0,3.0,0.6

In [2979]:
# train_fifa.loc[422]

In [2980]:
# train_fifa.loc[422]

In [2981]:
train_fifa.reset_index(drop=True, inplace=True)

In [2982]:
train_fifa['home_team'] = train_fifa['home_team'].str.replace('United States', 'Usa', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('United States', 'Usa', regex=False)
train_fifa['home_team'] = train_fifa['home_team'].str.replace('German Dr', 'Germany', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('German Dr', 'Germany', regex=False)
train_fifa['home_team'] = train_fifa['home_team'].str.replace('Germany Fr', 'Germany', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('Germany Fr', 'Germany', regex=False)
train_fifa['home_team'] = train_fifa['home_team'].str.replace('Western Australia', 'Australia', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('Western Australia', 'Australia', regex=False)
train_fifa['home_team'] = train_fifa['home_team'].str.replace('Czech Republic', 'Czechia', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('Czech Republic', 'Czechia', regex=False)
train_fifa['away_team'] = train_fifa['away_team'].str.replace('Czechoslovakia', 'Czechia', regex=False)
train_fifa['home_team'] = train_fifa['home_team'].str.replace('Czechoslovakia', 'Czechia', regex=False)

In [2983]:
train_fifa.shape

(40456, 11)

In [2984]:
train_fifa.columns.to_list()

['home_team',
 'away_team',
 'home_score',
 'away_score',
 'Result',
 'home_form',
 'away_form',
 'home_avg_goal',
 'away_avg_goal',
 'home_avg_form',
 'away_avg_form']

In [2985]:
train_set = train_fifa[['home_team',
 'away_team',
 'home_avg_goal',
 'away_avg_goal',
 'home_avg_form',
 'away_avg_form']]
output = train_fifa[ 'Result']

In [2986]:
train_set

,home_team,away_team,home_avg_goal,away_avg_goal,home_avg_form,away_avg_form
0,Argentina,Croatia,2.2,1.4,2.0,1.2
1,Brazil,Switzerland,1.6,1.2,2.4,1.2
2,Netherlands,Mexico,2.0,0.8,2.2,1.2
3,Croatia,Mexico,1.8,1.0,2.2,1.2
4,Uruguay,England,1.2,1.2,2.0,1.6
...,...,...,...,...,...,...
40451,Scotland,England,6.0,4.6,3.0,1.2
40452,England,Scotland,1.8,3.6,1.2,2.4
40453,Scotland,England,5.6,4.4,3.0,1.2
40454,England,Scotland,2.0,2.8,1.4,2.0
40455,Scotland,England,5.0,2.0,3.0,0.6

In [2987]:
X_train, X_test, y_train, y_test = train_test_split(train_set[['home_avg_goal',
 'away_avg_goal',
 'home_avg_form',
 'away_avg_form']], output, test_size=0.1, random_state=42)

In [2988]:
from xgboost import XGBClassifier

In [2989]:
model = RandomForestClassifier()
model2 = XGBClassifier()

In [2990]:
from sklearn.preprocessing import StandardScaler

In [2991]:
scaler = StandardScaler()

In [2992]:
X_train_scd = scaler.fit_transform(X_train)

In [2993]:
X_test_scd = scaler.transform(X_test)

In [2994]:
model.fit(X_train_scd, y_train)

RandomForestClassifier()

In [2995]:
model2.fit(X_train_scd, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [2996]:
prediction = model.predict(X_test)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [2997]:
prediction2 = model2.predict(X_test)

In [2998]:
prediction

array([2, 2, 2, ..., 1, 2, 2], shape=(4046,))

In [2999]:
prediction2

array([2, 2, 2, ..., 2, 2, 2], shape=(4046,))

In [3000]:
from sklearn.metrics import accuracy_score

In [3001]:
# y_test

In [3002]:
# len(model.predict_proba(X_test)[0])

In [3003]:
import joblib

In [3004]:
joblib.dump(model, "fifa_model3.pkl")

['fifa_model3.pkl']

In [3005]:
joblib.dump(train_set, "fifa_dataset3.pkl")

['fifa_dataset3.pkl']

In [3006]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [3007]:
X_train

       home_avg_goal  away_avg_goal  home_avg_form  away_avg_form
18552            0.6            0.2            0.8            0.2
17436            2.0            1.6            1.8            2.0
32968            1.6            1.4            1.2            1.0
1282             1.2            1.0            2.0            2.0
36079            1.8            3.4            1.4            2.4
...              ...            ...            ...            ...
6265             1.8            2.2            1.4            1.8
11284            2.2            2.4            2.4            2.4
38158            2.2            2.0            1.0            1.8
860              1.4            1.0            2.4            1.4
15795            1.0            1.2            2.0            2.6

[36410 rows x 4 columns]

In [3008]:
train_set

,home_team,away_team,home_avg_goal,away_avg_goal,home_avg_form,away_avg_form
0,Argentina,Croatia,2.2,1.4,2.0,1.2
1,Brazil,Switzerland,1.6,1.2,2.4,1.2
2,Netherlands,Mexico,2.0,0.8,2.2,1.2
3,Croatia,Mexico,1.8,1.0,2.2,1.2
4,Uruguay,England,1.2,1.2,2.0,1.6
...,...,...,...,...,...,...
40451,Scotland,England,6.0,4.6,3.0,1.2
40452,England,Scotland,1.8,3.6,1.2,2.4
40453,Scotland,England,5.6,4.4,3.0,1.2
40454,England,Scotland,2.0,2.8,1.4,2.0
40455,Scotland,England,5.0,2.0,3.0,0.6

In [3009]:
home_set = train_set[train_set['home_team'] == 'Nigeria'].iloc[0]

In [3010]:
X_train.columns.to_list()

['home_avg_goal', 'away_avg_goal', 'home_avg_form', 'away_avg_form']

In [3011]:
 match = {
        'home_avg_goal': train_set['home_avg_goal'], 'away_avg_goal': train_set['away_avg_goal'], 'home_avg_form':train_set['home_avg_form'], 'away_avg_form':train_set['away_avg_form']
        }

In [3012]:
# model.predict(match)